add enable_detailed_report flag to payload
ufcg-lsd/asperathos-integration-tests pull request #17
Opened 2019-07-16 19:08 UTC by javanlacerda

2019-07-17 16:17 UTC, joseims approved these changes

2019-07-17 16:46 UTC, matheuscmelo requested changes
Just a question

2019-07-17 16:46 UTC, matheuscmelo commented on assets/payload.json
> +        "enable_detailed_report": true,
Should it be `false` by default?

2019-07-18 16:56 UTC, joseims commented on assets/payload.json
> +        "enable_detailed_report": true,
Agreed

2022-03-08 13:11 UTC, closed without merging